Implement API endpoint for retrieving progress document by user or task for a particular date
Real-Dev-Squad/website-backend pull request #1089
Opened 2023-05-15 16:20 UTC by heyrandhir

This pull request introduces a new API endpoint, `/progresses/:type/:typeId/date/:date`, which allows the retrieval of progress documents based on a specific user ID or task ID and a specified date. The endpoint responds with the progress document corresponding to the provided user or task and date.

i.e `/progresses/user/:userId/date/:date` and `/progresses/task/:taskId/date/:date` 

It responds with the data as follows :

2023-05-16 12:33 UTC, Pratiyushkumar commented on routes/progresses.js
> +router.get("/:type/:typeId/date/:date", validateGetDayProgressParams, getProgressBydDateController);
why have we included date/:date, won't it work only with /:date

2023-05-16 13:03 UTC, heyrandhir commented on routes/progresses.js
> +router.get("/:type/:typeId/date/:date", validateGetDayProgressParams, getProgressBydDateController);
> does :typeId contains userId/taskId?

Yes it means if the type is user then userId and if type is task then taskId

2023-05-16 13:07 UTC, heyrandhir commented on routes/progresses.js
> +router.get("/:type/:typeId/date/:date", validateGetDayProgressParams, getProgressBydDateController);
> why have we included date/:date, won't it work only with /:date

Including the `date` keyword in the API endpoint `/progresses/:type/:typeId/date/:date` provides a clear and unambiguous way to indicate that the `date` parameter is specifically related to the progress of a particular `type` and `typeId`. 

By including the `date` keyword in the endpoint, we can ensure that the endpoint is more clearly and precisely defined, avoiding any potential confusion and improves the readability and maintainability of the API.

2023-05-16 14:33 UTC, Pratiyushkumar approved these changes
My doubts are clear hence looks good to me

2023-05-16 19:53 UTC, DashDeipayan requested changes

2023-05-16 19:53 UTC, DashDeipayan commented on middlewares/validators/progresses.js
> +    type: joi.string().valid("user", "task").required().messages({
Isn't separating these types into a separate Array do better. Incase we need to add more entities. Or, are you sure there wont be any more types in future?

2023-05-17 14:16 UTC, DashDeipayan commented
Looks good to me

2023-05-17 14:19 UTC, DashDeipayan approved these changes

2023-05-18 00:29 UTC, merged