Get Task dependency
Real-Dev-Squad/website-backend pull request #1099
Opened 2023-05-18 00:27 UTC by vinit717

close #1098 
Merge this  Pr first: https://github.com/Real-Dev-Squad/website-backend/pull/1070
![image](https://github.com/Real-Dev-Squad/website-backend/assets/111434418/d59407ea-b9f3-4e45-904e-e6d50818a57b)

2023-05-20 12:46 UTC, bhtibrewal submitted a review, later dismissed
looks okay to me

2023-05-21 10:57 UTC, heyrandhir submitted a review, later dismissed

2023-05-23 14:49 UTC, heyrandhir requested changes

2023-05-23 14:49 UTC, heyrandhir commented on controllers/tasks.js
> +      taskData: { ...taskData, dependsOn: dependencyDocReference },
can we cal it simply `data` instead of `taskData` ?

2023-05-24 00:11 UTC, heyrandhir approved these changes

2023-05-24 00:41 UTC, merged