add timestamp for login signup
Real-Dev-Squad/website-backend pull request #1139
Opened 2023-06-06 01:01 UTC by RitikJaiswal75

As per recent events happening in the community, we need to save the timestamp for the users when they signup/create an account with github.

2023-06-06 01:38 UTC, heyrandhir approved these changes
LGTM

2023-06-06 01:54 UTC, sahsisunny commented on controllers/auth.js
> +        githubLinked: Date.now(),
```suggestion
        githubLinkedOn: Date.now(),
```

2023-06-06 01:57 UTC, sahsisunny commented
Will we add it to the data model as well if so where is the ticket? and also link the issue ticket, please.

2023-06-06 02:12 UTC, sahsisunny submitted a review, later dismissed

2023-06-06 02:16 UTC, sahsisunny approved these changes

2023-06-06 02:22 UTC, heyrandhir approved these changes
LGTM

2023-06-06 18:10 UTC, prakashchoudhary07 commented
Why are we doing this?
Where do we need this?
How are we going to use it?

2023-06-06 18:13 UTC, prakashchoudhary07 commented on controllers/auth.js
> +        githubLinkedOn: Date.now(),
Why are we adding this?

2023-06-06 20:13 UTC, RitikJaiswal75 commented
hey @prakashchoudhary07 
Here are the answers to your questions

> Why are we doing this?

We are doing this as we want to know when did users sign up to rds 

> Where do we need this?

We will be needing this when we create an API for discord and user linking

> How are we going to use it?

we will use it when we want to kick the users from Discord using the Discord bot

Clubbing the information for an overview
We are moving towards the next phase of RDS where we want easier actions to kick out users from rds.
these timestamps will help us identify when did the user join rds and then we can categorize them as new/old which would help in efficient tracking.

2023-06-18 22:46 UTC, DashDeipayan requested changes
Incomplete tests

2023-06-19 15:47 UTC, j24m commented
### Test Coverage Stats :
![image](https://github.com/Real-Dev-Squad/website-backend/assets/53934353/f23ab08f-7762-4c91-8fba-e95aa0334ae5)

2023-07-29 08:57 UTC, sahsisunny commented
Closed as per discussion with @RitikJaiswal75

2023-07-29 08:57 UTC, closed without merging