pagination capability for PRs API
Real-Dev-Squad/website-backend pull request #120
Opened 2021-01-06 05:07 UTC by aman7870

I did the changes for getting the selected page value from user

2021-01-06 05:12 UTC, swarajpure requested changes
Checks are failing

Please do `npm run lint-fix` to fix the errors and commit again

2021-01-06 05:38 UTC, aman7870 commented
fixed the build errors

2021-01-06 07:19 UTC, swarajpure requested changes
Please pass a default value of 1 in function call
Otherwise if the user simply calls `pullrequests/open` without `page` as query, a blank response will be returned.

2021-01-06 12:57 UTC, aman7870 commented
fixed the page number to be 1 by default

2021-01-06 13:15 UTC, swarajpure requested changes

2021-01-06 13:15 UTC, swarajpure commented on controllers/pullRequestsController.js
> +    const { data } = await githubService.fetchOpenPRs(pageNumber)
There is a better and short way to pass default arguments

Please have a look here:
https://github.com/Real-Dev-Squad/website-backend/blob/d17ea626918d1424cc8ebd8181794c572e96ac24/models/users.js#L60

Also, please make sure to convert the argument to integer using `parseInt` as done in above function.

2021-01-08 14:33 UTC, aman7870 commented
did the changes do check

2021-01-08 15:31 UTC, swarajpure requested changes
Just one final, simple change and we'll be able to merge it!

2021-01-08 15:31 UTC, swarajpure commented on controllers/pullRequestsController.js
> +    const { data } = await githubService.fetchOpenPRs(pageNumber)
Can we simply pass it to the function than saving it in variable and then passing it?
`fetchOpenPRs(req.query.page || 1)` would be short and sweet

2021-01-08 15:54 UTC, aman7870 commented
did the changes do check

2021-01-08 16:31 UTC, swarajpure approved these changes
Great job!
Thank you! 🎉

2021-01-08 16:31 UTC, merged