Refactor controller functions to use service layer for retrieving user data (/users/userId/:userId) route (/users/self) route
Real-Dev-Squad/website-backend pull request #1249
Opened 2023-07-08 04:52 UTC by mailmesriza98

This closes https://github.com/Real-Dev-Squad/website-backend/issues/1235 and https://github.com/Real-Dev-Squad/website-backend/issues/1236

(/users/userId/:userId) route
(/users/self) route

![251230948-c188936a-b556-43cd-967d-2e0846da0984](https://github.com/Real-Dev-Squad/website-backend/assets/22434603/abf80027-f297-4d79-93b2-974c7df44b53)

2023-07-16 05:21 UTC, prakashchoudhary07 commented on controllers/users.js
> -
Please confirm if, the phone(88xxxxxxxx) and email (sommailxxxxxxxx.xx) being removed will break any frontend app, where it's being used

2023-07-16 05:23 UTC, prakashchoudhary07 commented on controllers/users.js
> +    // replace below line woth call to retrieveUsers(id)
If its a todo comment then please add a TODO prefix to it and create a new issue for it

2023-07-20 10:14 UTC, fakhruddinkw reviewed
Are we retrieving single user or multiple here?

2023-07-20 16:08 UTC, bksh05 approved these changes
LGTM

2023-07-21 00:26 UTC, bharati-21 commented
Please attach coverage

2023-07-22 09:36 UTC, iamitprakash requested changes

2023-07-22 09:36 UTC, iamitprakash commented on controllers/users.js
> +  const user = result.user;
are you sure, result can't be null here in any edge case..?

2023-07-22 19:19 UTC, iamitprakash approved these changes

2023-07-23 05:10 UTC, heyrandhir approved these changes

2023-07-23 12:27 UTC, merged