Refactor GET /users/isUsernameAvailable/:username route and /:username route to use service layer
Real-Dev-Squad/website-backend pull request #1264
Opened 2023-07-12 08:21 UTC by mailmesriza98

closes https://github.com/Real-Dev-Squad/website-backend/issues/1237 and https://github.com/Real-Dev-Squad/website-backend/issues/1240

2023-07-15 05:12 UTC, heyrandhir requested changes

2023-07-15 05:12 UTC, heyrandhir commented on services/dataAccessLayer.js
> +const retrieveUsers = async ({ id = null, username = null, usernames = null, query = null }) => {
can we use camel cases for username and usernames

2023-07-15 05:12 UTC, heyrandhir commented on controllers/users.js
> +    const user = result.user;
this user object will contain phone, email which we should remove

2023-07-15 05:12 UTC, heyrandhir commented on test/unit/services/dataAccessLayer.test.js
> +        expect(userData[12]).to.not.have.property(key);
we should assert `result.user` instead of userData[12]

2023-07-17 15:03 UTC, heyrandhir approved these changes

2023-07-18 05:20 UTC, iamitprakash approved these changes

2023-07-19 16:59 UTC, prakashchoudhary07 approved these changes

2023-07-19 16:59 UTC, merged