ts- testing
Real-Dev-Squad/website-backend pull request #1330
Opened 2023-07-26 17:53 UTC by vvaibhavdesai

2023-07-26 19:23 UTC, RitikJaiswal75 approved these changes

2023-07-26 19:26 UTC, RitikJaiswal75 requested changes
Code looks good but please fix the prettier issues to run tests without errors.

2023-07-27 03:57 UTC, vinayak-trivedi submitted a review, later dismissed
LGTM

2023-07-27 16:19 UTC, DashDeipayan approved these changes
LGTM

2023-07-27 16:26 UTC, RitikJaiswal75 approved these changes

2023-07-27 16:26 UTC, merged