Remove userStatus feature flag
Real-Dev-Squad/website-backend pull request #1358
Opened 2023-08-02 02:35 UTC by heyrandhir

Remove userStatus Feature Flag.

2023-08-02 05:42 UTC, sahsisunny approved these changes

2023-08-02 14:02 UTC, iamitprakash approved these changes

2023-08-03 22:55 UTC, sahsisunny approved these changes

2023-08-04 09:38 UTC, iamitprakash requested changes
test case stats missing

2023-08-04 18:14 UTC, iamitprakash requested changes
please add test case stats

2023-08-05 04:00 UTC, heyrandhir commented
> please add test case stats

Added validator and controller file testing stats. the files which I modified. Thanks.

2023-08-05 21:52 UTC, iamitprakash approved these changes

2023-08-06 08:15 UTC, merged