[Live-Site] feat: added api to kickout peer
Real-Dev-Squad/website-backend pull request #1375
Opened 2023-08-07 01:41 UTC by prerana1821

# Issues

Fixes #1374

2023-08-08 09:07 UTC, iamitprakash requested changes

2023-08-08 09:07 UTC, iamitprakash commented on controllers/events.js
> +      message: `Peer is kicked out from the event`,
Selected Participant is removed from event

2023-08-08 09:07 UTC, iamitprakash commented on controllers/events.js
> +      message: "Couldn't kickout peer from the event. Please try again later",
You can't remove selected Participant from Remove, Please ask Admin or Host for help

2023-08-08 09:07 UTC, iamitprakash commented on middlewares/validators/events.js
> +    logger.error(`Error while removing a peer from the event: ${error}`);
We encountered some error while removing selected Participant from event

2023-08-08 09:07 UTC, iamitprakash commented on models/events.js
> +      throw new Error("Peer is not part of the specified event");
replace Peer with Participants

2023-08-08 12:29 UTC, prerana1821 commented on models/events.js
> +      throw new Error("Peer is not part of the specified event");
Done. Thank you

2023-08-08 16:34 UTC, vvaibhavdesai commented on controllers/events.js
> + * @throws {Object} The JSON response with an error message if an error occurred while kicking out the peer.
where are we throwing error in the below function

2023-08-08 16:34 UTC, vvaibhavdesai commented on controllers/events.js
> +      message: `Selected Participant is removed from event.`,
put all the strings in constant

2023-08-09 21:28 UTC, iamitprakash approved these changes

2023-08-09 21:28 UTC, merged