Fix for the issue: Github issue link is to be displayed on the task details page. #774
Real-Dev-Squad/website-backend pull request #1383
Opened 2023-08-07 17:37 UTC by kapillondhe

Allow GitHub issue link from the client request. This will store the issue html URL in the database.

2023-08-09 08:12 UTC, sahsisunny requested changes
Where is the test?

2023-08-16 17:54 UTC, kapillondhe commented
> Where is the test?

Added the tests. Thanks.

2023-08-18 12:19 UTC, vinit717 commented on test/unit/middlewares/tasks-validator.test.js
please fix the test and the lint also 
And no need to to write unnecessary test

2023-08-19 18:15 UTC, kapillondhe commented
PR #1428 Raised.

2023-08-19 18:15 UTC, closed without merging