completed validation of verify status
Real-Dev-Squad/website-backend pull request #1393
Opened 2023-08-10 15:38 UTC by shreya-mishra

2023-08-11 15:06 UTC, DashDeipayan requested changes

2023-08-11 15:17 UTC, shreya-mishra commented on controllers/auth.js
> +    const userId = req.query.user_id;
resolved it in last commit

2023-08-11 15:17 UTC, shreya-mishra commented on controllers/auth.js
> +      data: { device_info: userDeviceInfoData.data.device_info },
resolved it in last commit

2023-08-11 15:17 UTC, shreya-mishra commented on middlewares/validators/qrCodeAuth.js
> +    logger.error(`Invalid Query Parameters Passed`);
I agree , resolved it in last commit

2023-08-11 15:17 UTC, shreya-mishra commented on middlewares/validators/qrCodeAuth.js
> +    res.boom.badRequest(`Invalid Query Parameters Passed`);
+1

2023-08-13 16:14 UTC, shreya-mishra commented
Raised a different PR https://github.com/Real-Dev-Squad/website-backend/pull/1400

2023-08-13 16:14 UTC, closed without merging