feat/oooCommand: route added to get user by discordId for oooCommand
Real-Dev-Squad/website-backend pull request #1411
Opened 2023-08-13 11:13 UTC by palakgupta2712

2023-08-13 15:00 UTC, sahsisunny commented
Add test coverage of your changes and link issue ticket as well.

2023-08-14 19:45 UTC, lakshayman requested changes

2023-08-14 19:45 UTC, lakshayman commented on controllers/users.js
> +    const discordId = Number(req.params.discordId);
NIT: Are we not using any validator, as here we are converting it explicitly?

2023-08-14 19:45 UTC, lakshayman commented
Few tests are failing

2024-01-25 13:56 UTC, closed without merging