feat: OOO nickname change
Real-Dev-Squad/website-backend pull request #1461
Opened 2023-08-29 07:03 UTC by bharati-21

# Test: 1119 Update User Nickname During OOO

### Closes: https://github.com/Real-Dev-Squad/website-backend/issues/1119

- The following PR contains changes related to the RDS discord server nickname change when a user is on OOO.
- The updates are reflected when the `PATCH /users/status/batch` API is triggered.

### Test Cases
- The tests for this PR are in #1460

2023-08-29 19:07 UTC, heyrandhir requested changes

2023-08-29 19:07 UTC, heyrandhir commented on services/usersStatusService.ts
> +    await response.text();
do we need this if we are not returning. we can remove it if we don't require it.

2023-08-29 19:07 UTC, heyrandhir commented on utils/userStatus.js
> +    oooMessage = `(OOO ${untilMonth} ${untilDay})`;
do we have a case where the user only gives until date and not from ?

2023-08-29 19:07 UTC, heyrandhir commented on utils/userStatus.js
> +const generateOOONickname = (username, from, until) => {
we can wrap the code inside the function in a try catch block

2023-08-29 19:07 UTC, heyrandhir commented on utils/userStatus.js
> +    if (errorsLen) {
we are only sending the error metric. what about the success metric i.e how many user names were updated successfully.

2023-08-29 23:27 UTC, DashDeipayan requested changes

2023-08-29 23:27 UTC, DashDeipayan commented on services/usersStatusService.ts
> +    await response.text();
Should be returning something atleast, something like `{success:true}`

2023-08-29 23:27 UTC, DashDeipayan commented on utils/userStatus.js
> +    const updates = await Promise.allSettled(usersNicknameUpdates);
Why `Promise.allSettled()` instead of `Promise.all()`

2023-08-30 15:08 UTC, closed without merging

2023-08-30 15:08 UTC, bharati-21 commented
Closing thi

2023-08-30 15:11 UTC, bharati-21 commented
Closing this PR as a scheduled cron job needs to be created for the nickname change.