feat: join changes in events in live-site
Real-Dev-Squad/website-backend pull request #1467
Opened 2023-08-31 09:49 UTC by satyam73

This PR contains the changes that were needed for onboarding flow change in `live-site`.

2023-08-31 10:21 UTC, Pratiyushkumar reviewed
please give some context in the PR description as to what are you trying to solve and other stuff that can give the reviewer idea about your task

2023-08-31 17:47 UTC, iamitprakash requested changes

2023-08-31 19:13 UTC, satyam73 commented on controllers/events.js
>  const joinEvent = async (req, res) => {
Yes @iamitprakash , I've actually used the active event id and passed it to tokenService.getAuthToken() by destructuring and passed {roomId: eventId}, you can see line 101 I've assigned eventId with active event id

2023-09-01 06:33 UTC, Pratiyushkumar approved these changes
LGTM

2023-09-01 14:05 UTC, yesyash approved these changes

2023-09-01 14:07 UTC, yesyash commented on routes/events.js
> +  "/end",
- Please make a ticket for this @satyam73

2023-09-01 14:14 UTC, merged