feat : add jsdoc
Real-Dev-Squad/website-backend pull request #1472
Opened 2023-09-02 07:37 UTC by Aryex82

2023-09-05 14:46 UTC, Pratiyushkumar commented
can you add postman output by sending a request and getting a response for some visual understanding of the feature you are building.

2023-09-06 20:08 UTC, satyam73 requested changes

2023-09-07 08:22 UTC, Aryex82 commented on models/users.js
> + * @param usersData {Array} - Users list as an array. Each element of user list should contain a property called id(PK)
Primary Key.

2023-09-07 08:27 UTC, Aryex82 commented on models/users.js
> + * @param usersData {Array} - Users list as an array. Each element of user list should contain a property called id(PK)
I've updated the doc.

2023-09-07 16:46 UTC, sahsisunny commented
Can you also mention the PR for updating the doc like API contracts?

2023-09-08 18:23 UTC, satyam73 approved these changes
LGTM

2023-09-08 21:42 UTC, Achintya-Chatterjee approved these changes

2023-09-08 21:52 UTC, merged