Route `tasks/self` for fetching all tasks of the user
Real-Dev-Squad/website-backend pull request #152
Opened 2021-01-30 11:50 UTC by Rucha1499

created a new route `tasks/self` for fetching all the tasks of the  user

2021-01-30 19:56 UTC, ankurnarkhede requested changes
LGTM.
@Rucha1499 , can you add tests for this?
Also need to generate the API schema for the updated routes.

2021-01-31 05:33 UTC, swarajpure requested changes

2021-01-31 05:33 UTC, swarajpure commented on controllers/tasksController.js
> +const getSelfTasks = async (req, res) => {
Please add JSDoc

2021-01-31 05:48 UTC, Rucha1499 commented on controllers/tasksController.js
> +const getSelfTasks = async (req, res) => {
Okay! Thank you.

2021-01-31 05:52 UTC, Rucha1499 commented
> LGTM.
> @Rucha1499 , can you add tests for this?
> Also need to generate the API schema for the updated routes.

Okay! I will do the changes. 👍

2021-02-01 13:29 UTC, swarajpure submitted a review, later dismissed
Looks good to me!

2021-02-10 14:44 UTC, sumitd94 approved these changes
Thanks, Looks good to me!

2021-02-12 15:33 UTC, ankurnarkhede approved these changes

2021-02-12 15:33 UTC, merged

2021-02-12 16:24 UTC, sumitd94 commented on models/tasks.js
> +const fetchUserActiveAndBlockedTasks = async (username) => {
This is causing a production issue