Test: 1119 OOO nickname update
Real-Dev-Squad/website-backend pull request #1545
Opened 2023-09-22 12:38 UTC by bharati-21

# Feat: 1119 Update User Discord Nickname During OOO

### Closes: https://github.com/Real-Dev-Squad/website-backend/issues/1119

- The following PR contains tests for the changes in [this PR](https://github.com/Real-Dev-Squad/website-backend/pull/1544) to update nickname for the user during OOO.

2023-09-23 08:30 UTC, iamitprakash requested changes
please add test case stats AFER and BEFORE

2023-09-29 05:54 UTC, shubhamsigdar1 approved these changes

2023-09-29 17:51 UTC, bharati-21 commented
> please add test case stats AFTER and BEFORE

Added coverage.

2023-09-30 08:19 UTC, iamitprakash approved these changes

2023-09-30 09:42 UTC, Achintya-Chatterjee approved these changes

2023-10-01 06:43 UTC, merged