returning `phone` and `email` only for users/self route when query `private` is true
Real-Dev-Squad/website-backend pull request #156
Opened 2021-02-02 17:41 UTC by swarajpure

Fixes #155 

According to the API contract: https://github.com/Real-Dev-Squad/website-api-contracts/pull/23

2021-02-05 18:37 UTC, ankurnarkhede requested changes
@swarajpure , as per the conversation with @ankushdharkar , we will go forward with the private query param.
Can you add tests for this change?
We can merge his post that.

2021-02-07 10:09 UTC, swarajpure commented
> 
> 
> @swarajpure , as per the conversation with @ankushdharkar , we will go forward with the private query param.
> Can you add tests for this change?
> We can merge his post that.

Tests added!

2021-02-07 15:43 UTC, ankurnarkhede requested changes

2021-02-07 15:43 UTC, ankurnarkhede commented on test/integration/usersController.test.js
> +    it('Should return the logged user\'s details with phone and email', function (done) {
@swarajpure, can you add this test in the earlier describe block? We do not need a separate describe block for this. Its the same route.

2021-02-07 16:58 UTC, ankurnarkhede approved these changes

2021-02-07 16:58 UTC, merged