Authorization app owners
Real-Dev-Squad/website-backend pull request #157
Opened 2021-02-03 17:04 UTC by Harshi7016

PR for Authorize the user for post and update of the tasks #141 new PR

2021-02-05 17:51 UTC, Harshi7016 commented
Sorry for too many commits , I will be raising a new PR once the tests get passed

2021-02-05 20:24 UTC, Harshi7016 commented on controllers/usersController.js
> +    // const allUsers = await userQuery.fetchUsers(req.query)
remove comments

2021-02-05 20:24 UTC, Harshi7016 commented on controllers/usersController.js
> +    return res.boom.serverUnavailable('Something went wrong please contact admin')
error message: badImple- 500

2021-02-05 20:24 UTC, Harshi7016 commented on middlewares/authorizeOwner.js
> + * @todo: Add tests to assert on refreshed JWT generation by modifying the TTL values for the specific test. Currently not possible in the absence of a test-suite.
remove todo

2021-02-05 20:24 UTC, Harshi7016 commented on middlewares/authorizeOwner.js
> +      return res.boom.notFound('Unauthorized User')
403

2021-02-05 20:24 UTC, Harshi7016 commented on middlewares/authorizeOwner.js
> +    return res.boom.badImplementation('Unauthorized User')
check other middleware

2021-02-05 20:24 UTC, Harshi7016 commented on test/integration/tasksController.test.js
> +  let jwt = ''
let jwt;

2021-02-05 20:24 UTC, Harshi7016 commented on test/integration/tasksController.test.js
>    let tid = ''
let tid;

2021-02-05 20:24 UTC, Harshi7016 commented on test/integration/tasksController.test.js
> +        .set('cookie', `rds-session=${jwt}`)
create mock for forbidden with other user details

2021-02-27 02:16 UTC, ankurnarkhede commented
CI failing... @harshith-venkatesh

2021-02-27 02:17 UTC, ankurnarkhede requested changes
CI failing...

2021-02-27 02:53 UTC, harshith-venkatesh commented
@ankurnarkhede I will update the test cases today
Sorry for the delay

2021-03-13 10:37 UTC, ankurnarkhede commented
@harshith-venkatesh , this PR is pending since long. Can you check it?

2021-03-13 11:08 UTC, harshith-venkatesh commented
@ankurnarkhede , I am finding issue in creating test cases, Can I send PR without 403 error test case?

2021-03-13 18:27 UTC, harshith-venkatesh commented
Closing this PR on discussion with @ankurnarkhede and creating a new PR with CI being successful
@ankushdharkar

2021-03-13 18:27 UTC, closed without merging