fix: type error in task models
Real-Dev-Squad/website-backend pull request #1663
Opened 2023-11-02 16:24 UTC by sahsisunny

2023-11-02 16:43 UTC, vinit717 requested changes
Please follow PR format and add issue ticket

2023-11-02 17:03 UTC, vinit717 approved these changes

2023-11-02 17:07 UTC, gauravsinhaweb submitted a review, later dismissed

2023-11-02 17:41 UTC, iamitprakash requested changes
please cover if condition into test case

2023-11-03 06:37 UTC, iamitprakash approved these changes

2023-11-03 06:37 UTC, merged