Application api
Real-Dev-Squad/website-backend pull request #1732
Opened 2023-11-26 06:55 UTC by vinayak-trivedi

Date: 18/11/2023

----

## Issue Ticket Number:- 
- add issue ticket number here e.g #1282 

## Description: 
This PR creates three endpoints:
- GET: /applications: returns all the applications which are not accepted or rejected, and if userId is passed in the query param it return a application of a particular user
- POST: /applications: adds the application of a user to join RDS
- PATCH: /applications/:applicationId: updates a particular application, this will only be accessible to super_user,

Is Under Feature Flag 
- [] Yes
- [x] No

Database changes
- [x] Yes
- [ ] No

Breaking changes (If your feature is breaking/missing something please mention pending tickets)
- [ ] Yes
- [x] No

Is Development Tested?

- [x] Yes
- [ ] No

Tested in staging?

- [ ] Yes
- [x] No

**Api contract: ** https://github.com/Real-Dev-Squad/website-api-contracts/pull/142
**Data model doc: ** https://github.com/Real-Dev-Squad/website-data-models/pull/59/files

2023-11-26 07:37 UTC, vinit717 commented
Please add local working proof via Postman for every route

2023-12-05 00:07 UTC, vinit717 commented
Please add test stats

2023-12-05 16:02 UTC, heyrandhir requested changes
Kindly include unit tests and a route for `/applications/:id`. If time allows, consider implementing pagination for the GET all applications response.

2023-12-05 16:02 UTC, heyrandhir commented on test/fixtures/applications/applications.ts
> +  ];
Nit : can generate some meaningful text from chatgpt instead of some random text 😇

2023-12-09 00:26 UTC, vinayak-trivedi commented on controllers/applications.ts
> +    const applications = await ApplicationModel.getAllApplications();
https://github.com/Real-Dev-Squad/website-backend/issues/1761 created a different ticket for it

2023-12-09 11:43 UTC, heyrandhir reviewed
Don't see unit tests for the model function @vinayak-trivedi

2023-12-09 11:46 UTC, vinayak-trivedi commented
> Don't see unit tests for the model function @vinayak-trivedi

@heyrandhir as discussed, I will be adding pagination in separate PR, so there will be changes in models as well, so that is why not adding model test here

2023-12-26 00:33 UTC, closed without merging