Added middleware for requests route
Real-Dev-Squad/website-backend pull request #1868
Opened 2024-01-31 09:10 UTC by sahsisunny

2024-01-31 20:38 UTC, iamitprakash requested changes

2024-01-31 20:38 UTC, iamitprakash commented on middlewares/validators/oooRequests.ts
> +          "number.min": "from date must be greater than or equal to current date",
Today's date

2024-01-31 20:38 UTC, iamitprakash commented on middlewares/validators/requests.ts
> +        await createOooStatusRequestValidator(req as OooStatusRequestRequest, res as OooStatusRequestResponse, next);
what is this..?

2024-01-31 21:45 UTC, sahsisunny commented on middlewares/validators/oooRequests.ts
> +          "number.min": "from date must be greater than or equal to current date",
Done

2024-01-31 21:46 UTC, sahsisunny commented on middlewares/validators/requests.ts
> +        await createOooStatusRequestValidator(req as OooStatusRequestRequest, res as OooStatusRequestResponse, next);
OOO request type of the request.

2024-02-01 20:40 UTC, iamitprakash approved these changes

2024-02-03 17:38 UTC, iamitprakash approved these changes

2024-02-03 17:40 UTC, merged