Added model function for ooo requests
Real-Dev-Squad/website-backend pull request #1869
Opened 2024-01-31 10:17 UTC by sahsisunny

2024-01-31 20:40 UTC, iamitprakash requested changes

2024-01-31 20:40 UTC, iamitprakash commented on constants/oooRequest.ts
> +export const ERROR_WHILE_CREATING_OOO_REQUEST = "Error while creating ooo request";
OOO

2024-01-31 20:40 UTC, iamitprakash commented on models/oooRequests.ts
> +    const doc = await oooRestModel.add(request);
what is this...?

2024-01-31 21:46 UTC, sahsisunny commented on constants/oooRequest.ts
> +export const ERROR_WHILE_CREATING_OOO_REQUEST = "Error while creating ooo request";
Fixed

2024-01-31 21:47 UTC, sahsisunny commented on models/oooRequests.ts
> +    const doc = await oooRestModel.add(request);
Response doc object of the model

2024-02-01 20:48 UTC, iamitprakash approved these changes

2024-02-03 17:30 UTC, merged