Added controller for request and ooo requests API
Real-Dev-Squad/website-backend pull request #1870
Opened 2024-01-31 12:05 UTC by sahsisunny

2024-01-31 20:45 UTC, iamitprakash requested changes

2024-01-31 20:45 UTC, iamitprakash commented on controllers/oooRequests.ts
> +    const userId = req.userData.id;
what if req is null or userData is null

2024-01-31 20:45 UTC, iamitprakash commented on controllers/oooRequests.ts
> +        const oooRequestDoc = await createOooRequest({userId, ...oooRequestBody});
oooRequestDoc please use better name

2024-01-31 20:45 UTC, iamitprakash commented on controllers/oooRequests.ts
> +                    createdAt: Date.now(),
don't we need to convert date into specific timezone

2024-01-31 20:45 UTC, iamitprakash commented on controllers/requests.ts
> +  req: OooStatusRequestRequest,
please change this

2024-01-31 21:49 UTC, sahsisunny commented on controllers/oooRequests.ts
> +    const userId = req.userData.id;
Done , added null check condition

2024-01-31 22:32 UTC, sahsisunny commented on controllers/oooRequests.ts
> +        const oooRequestDoc = await createOooRequest({userId, ...oooRequestBody});
Done

2024-01-31 22:46 UTC, sahsisunny commented on controllers/requests.ts
> +  req: OooStatusRequestRequest,
Done

2024-02-01 20:46 UTC, iamitprakash approved these changes

2024-02-03 17:30 UTC, merged