Tests/requests 1
Real-Dev-Squad/website-backend pull request #1885
Opened 2024-02-10 17:08 UTC by palakgupta2712

Date: 10/02/2024

Developer Name: Palak Gupta (palakgupta2712)

---

## Issue Ticket Number

closes #1874 

## Description

### Documentation Updated?

- [ ] Yes
- [x] No

### Under Feature Flag

- [ ] Yes
- [x] No

### Database Changes

- [ ] Yes
- [x] No

### Breaking Changes

- [ ] Yes
- [ ] No

### Development Tested?

- [ ] Yes
- [ ] No

## Test Coverage
Units
![image](https://github.com/Real-Dev-Squad/website-backend/assets/61227144/c853e7c8-b31a-44e7-8e63-3307e5292664)

Integration
![image](https://github.com/Real-Dev-Squad/website-backend/assets/61227144/7b093c5f-13c0-47ac-b07c-d25bddadd3d4)

2024-02-10 18:18 UTC, iamitprakash requested changes
can we write better PR title

2024-02-11 13:04 UTC, sahsisunny commented on test/integration/requests.test.ts
> +    it("should update a request", function (done) {
Test title should be different

2024-02-12 00:07 UTC, Achintya-Chatterjee approved these changes

2024-02-12 01:36 UTC, Achintya-Chatterjee requested changes

2024-02-12 01:36 UTC, Achintya-Chatterjee commented on test/unit/models/requests.test.ts
> +    it("should add a new OOO request to the database", async () => {
instead of `should add a new OOO request to the database,` We could use a more descriptive name like `should successfully create a new OOO request.`

2024-02-12 01:44 UTC, sahsisunny approved these changes

2024-02-12 01:46 UTC, Achintya-Chatterjee approved these changes

2024-02-12 18:28 UTC, iamitprakash approved these changes

2024-02-12 18:28 UTC, merged