Remove condition for updating task for verified task status and perce…
Real-Dev-Squad/website-backend pull request #1937
Opened 2024-03-03 08:49 UTC by skv93-coder

…nt bar completion condition

Date: 

Developer Name: 

---

## Issue Ticket Number

## Description

### Documentation Updated?

- [ ] Yes
- [ ] No

### Under Feature Flag

- [ ] Yes
- [ ] No

### Database Changes

- [ ] Yes
- [ ] No

### Breaking Changes

- [ ] Yes
- [ ] No

### Development Tested?

- [ ] Yes
- [ ] No

## Screenshots
<details>
<summary>Screenshot 1</summary>

</details>

## Test Coverage
<details>
<summary>Screenshot 1</summary>

</details>

## Additional Notes

2024-03-08 00:49 UTC, Achintya-Chatterjee requested changes
@skv93-coder tests are failing, Kindly look into that. Rest all are looking good

2024-03-20 16:33 UTC, Achintya-Chatterjee commented on controllers/tasks.js
> +          return res.boom.badRequest("Task percentCompleted can't updated as status is COMPLETED");
here you used multiple conditional checks that can be consolidated into reusable functions. eg., you can create separate functions to handle status checks and progress checks.

2024-03-20 16:33 UTC, Achintya-Chatterjee commented on controllers/tasks.js
> +          return res.boom.badRequest("Task percentCompleted can't updated as status is COMPLETED");
here several nested conditional statements in the code can be simplified for better readability. Could you refactor these nested conditionals into smaller, more understandable blocks or switch-case statements?

2024-03-20 18:12 UTC, iamitprakash approved these changes

2024-03-21 19:26 UTC, Achintya-Chatterjee approved these changes

2024-03-22 07:22 UTC, merged