Add OOO  request approved  data to user future status
Real-Dev-Squad/website-backend pull request #2001
Opened 2024-04-04 15:08 UTC by sahsisunny

Date: 

Developer Name: 

---

## Issue Ticket Number

## Description

### Documentation Updated?

- [ ] Yes
- [ ] No

### Under Feature Flag

- [ ] Yes
- [ ] No

### Database Changes

- [ ] Yes
- [ ] No

### Breaking Changes

- [ ] Yes
- [ ] No

### Development Tested?

- [ ] Yes
- [ ] No

## Screenshots
<details>
<summary>Screenshot 1</summary>

</details>

## Test Coverage
<details>
<summary>Screenshot 1</summary>

</details>

## Additional Notes

2024-04-08 18:17 UTC, palakgupta2712 commented on models/userStatus.js
> +      if (userStatusData.futureStatus && userStatusData.futureStatus.state === "approved") {
can you please use constant here?

2024-04-08 18:18 UTC, palakgupta2712 requested changes

2024-04-09 01:24 UTC, sahsisunny commented on models/userStatus.js
> +    delete futureStatusData.userId;
which delete operator?

2024-04-09 18:28 UTC, Achintya-Chatterjee approved these changes

2024-04-09 19:01 UTC, palakgupta2712 commented on models/userStatus.js
> +    delete futureStatusData.userId;
delete futureStatusData.userId;

2024-04-10 01:13 UTC, sahsisunny commented on models/userStatus.js
> +    delete futureStatusData.userId;
I am using delete operator here, which delete operator should I use?

2024-04-10 01:13 UTC, sahsisunny commented on models/userFutureStatus.ts
> +export const createUserFutureStatus = async (body: UserFutureStatusType) => {
It's suggested by @lakshayman

2024-04-10 04:08 UTC, palakgupta2712 approved these changes

2024-04-10 21:46 UTC, merged