Creating new PR for resolving #200 no. PR
Real-Dev-Squad/website-backend pull request #201
Opened 2021-02-26 18:44 UTC by PremanandChowdhury

Resolving the PR [link](https://github.com/Real-Dev-Squad/website-backend/pull/200 "userinfo Crypto PR")

2021-02-27 02:09 UTC, ankurnarkhede commented
@Kratika0907 , the API contract https://github.com/Real-Dev-Squad/website-api-contracts/blob/28dc5d141c89a7a91cc37769d935dace7e30456b/crypto-site/README.md needs clarifications around the authorization.
Can you add it there?

2021-02-27 09:59 UTC, ankurnarkhede requested changes
I am waiting for @Kratika0907 to modify the contract.
In the meanwhile, @PremanandChowdhury , the PR doesn't have unit and integration tests.

2021-02-27 11:43 UTC, PremanandChowdhury commented
I'll Check the docs and write the Unit and Integration tests.

2021-03-04 14:15 UTC, PremanandChowdhury commented on models/crypto.js
> +      const user = await cryptoUserModel.where('user_id', '==', userId).get()
Crypto will have separate ``user`` model 👍🏼

2021-04-09 13:36 UTC, swarajpure commented on models/crypto.js
> +      const user = await cryptoUserModel.where('user_id', '==', userId).get()
We're still accessing `users` collection 🤔

2021-04-09 13:45 UTC, PremanandChowdhury commented on models/crypto.js
> +      const user = await cryptoUserModel.where('user_id', '==', userId).get()
For crypto IDK 😇

2023-11-06 00:36 UTC, closed without merging