Feature/api crypto get products
Real-Dev-Squad/website-backend pull request #208
Opened 2021-02-28 16:15 UTC by prakashchoudhary07

2021-03-02 17:10 UTC, Kratika0907 submitted a review, later dismissed

2021-03-06 10:31 UTC, ankurnarkhede requested changes

2021-03-06 10:31 UTC, ankurnarkhede commented on controllers/crypto.js
> +const getProducts = async (req, res) => {
Can we name the controller file as `cryptoController.js`, similar to other files?

2023-11-06 20:07 UTC, closed without merging

2023-11-06 20:08 UTC, prakashchoudhary07 commented
This is being deleted as the contracts were updated, and the project is on hold currently