[WIP] crypto - /auctions api
Real-Dev-Squad/website-backend pull request #225
Opened 2021-03-10 18:23 UTC by correaswebert

Creating the API for /auctions route under crypto.
You can create auctions, make bids, fetch auctions (by id and time)

2021-03-11 20:51 UTC, swarajpure reviewed
Great job! 🎉

2021-03-11 20:51 UTC, swarajpure commented on controllers/auctionController.js
> +    logger.info(auctionData)
Is line 17 needed?

2021-03-11 20:51 UTC, swarajpure commented on controllers/auctionController.js
> +    logger.info(auctionsBySeller)
re: logger

2021-03-11 20:51 UTC, swarajpure commented on controllers/auctionController.js
> +    const { initialPrice, item, duration, quantity } = req.body
No validation on incoming req.body?

2021-03-11 20:51 UTC, swarajpure commented on controllers/auctionController.js
> +    const { username: seller } = req.userData
We could use `id` from the userData and save that it DB

2021-03-11 20:51 UTC, swarajpure commented on controllers/auctionController.js
> +    const { username: bidderId } = req.userData
re: `id`

2021-03-11 20:51 UTC, swarajpure commented on controllers/auctionController.js
> +    const { bid } = req.body
re: validation

2021-03-11 20:51 UTC, swarajpure commented on controllers/auctionController.js
> +    const auctionsBySeller = await auctions.fetchAuctionBySeller(sellerId)
Need to be converted to `userId`

2021-03-11 20:51 UTC, swarajpure commented on models/auctions.js
> +    logger.info(`Made new bid ${bidRef.id}`)
re: logger

2021-03-11 20:51 UTC, swarajpure commented on routes/auctions.js
> +router.post('/create', authenticate, auctionController.createNewAuction)
Let's not keep line number 12 and 16

2021-03-11 20:51 UTC, swarajpure commented on routes/auctions.js
> +router.post('/create', authenticate, auctionController.createNewAuction)
Can we have swagger docs?

2021-03-13 10:08 UTC, ankurnarkhede requested changes
@swarajpure , can you run the generate schema command, then we can merge this.

2021-03-13 12:48 UTC, ankurnarkhede approved these changes
Tests Issue: https://github.com/Real-Dev-Squad/website-backend/issues/236

2021-03-13 12:48 UTC, ankurnarkhede commented
LGTM ✅

2021-03-13 12:48 UTC, merged

2021-03-13 19:58 UTC, ankushdharkar commented
Implements Real-Dev-Squad/website-todo-items#16