Add api to approve and reject onboarding extension requests
Real-Dev-Squad/website-backend pull request #2324
Opened 2024-12-28 20:00 UTC by pankajjs

Date: 29 Dec, 2024

Developer Name: @pankajjs 

---

## Issue Ticket Number

- Closes #2187 

## Description

### Documentation Updated?

- [ ] Yes
- [ ] No

### Under Feature Flag

- [x] Yes
- [ ] No

### Database Changes

- [x] Yes
- [ ] No

### Breaking Changes

- [ ] Yes
- [x] No

### Development Tested?

- [ ] Yes
- [ ] No

## Screenshots
<details>
<summary>Screenshot 1</summary>

</details>

## Test Coverage
<details>
<summary>Screenshot 1</summary>

</details>

## Additional Notes

2025-01-09 19:29 UTC, vikasosmium approved these changes

2025-01-12 11:45 UTC, shobhan-sundar-goutam requested changes

2025-01-12 11:52 UTC, pankajjs commented on controllers/onboardingExtension.ts
> +        });
Resolved

2025-01-12 11:55 UTC, pankajjs commented on controllers/onboardingExtension.ts
> +                createdAt: Date.now(),
Removed createdAt field because logs stores timestamp by default.

2025-01-12 13:56 UTC, shobhan-sundar-goutam approved these changes

2025-01-15 08:10 UTC, vikasosmium approved these changes

2025-01-16 17:49 UTC, merged