Created get/update wallet
Real-Dev-Squad/website-backend pull request #247
Opened 2021-03-14 20:09 UTC by prakashchoudhary07

2021-03-14 20:19 UTC, swarajpure commented on routes/index.js
> +app.use('/wallets', require('./wallets.js'))
`wallet` or `wallet`?

2021-03-14 20:25 UTC, sumitd94 approved these changes
Few NIT Comments, This was perfect FTL Work 🔥

2021-03-14 20:25 UTC, sumitd94 commented on controllers/walletsController.js
> + * Get the  contributions of the user
`Contributions`?

2021-03-14 20:25 UTC, sumitd94 commented on controllers/walletsController.js
> +    return res.status(200).json({
NIT: By default, it returns 200, we can return this like `res.json({})`

2021-03-14 20:25 UTC, sumitd94 commented on models/wallets.js
> +    }
NIT: we can destructure here and make it like this
```javascript
const { id } = await walletModel.add(walletData)
return {
id,
data: walletData
}
```

2021-03-14 20:25 UTC, sumitd94 commented on models/wallets.js
> +    let userWallet = await fetchWallet(userId)
NIT: If from `userWallet` we only need `id` then we can destructure only `id` here

2021-03-14 20:29 UTC, ankushdharkar commented on routes/wallets.js
> + *     summary: Gets the user walelt details
*wallet

2021-03-14 20:30 UTC, ankushdharkar commented on routes/index.js
> +app.use('/wallets', require('./wallets.js'))
I'd go with `wallet`

2021-03-14 20:32 UTC, ankushdharkar commented on models/wallets.js
> +      return { id: walletDocs.docs[0].id, ...walletDocs.docs[0].data() }
```const userWallet = walletDocs.docs[0];```

2021-03-14 20:39 UTC, ankushdharkar commented on models/wallets.js
> +    const userWallet = walletDocs.docs[0]
NIT: `const [ userWallet ] = walletDocs.docs;`

2021-03-14 20:41 UTC, ankushdharkar commented on models/wallets.js
> +    if ((!walletDocs.empty) && userWallet) {
Why do we need to check for `walletDocs.empty`?

2021-03-14 20:41 UTC, ankushdharkar commented on models/wallets.js
> +      userWallet = await fetchWallet(userId)
```js
 userWallet = await createWallet(userId)
 ```

2021-03-14 20:43 UTC, ankushdharkar commented on models/wallets.js
> +    const firestoreKeyName = {}
firestoreKeysObj

2021-03-14 20:52 UTC, ankushdharkar approved these changes

2021-03-14 20:53 UTC, merged

2021-03-14 20:54 UTC, ankurnarkhede requested changes

2021-03-14 20:54 UTC, ankurnarkhede commented on controllers/walletsController.js
> +    return res.status.json({
return res.json(...

2021-03-14 20:54 UTC, ankurnarkhede commented on models/wallets.js
> +      currency: {}
I am assuming the `currency` object will contain values like
```
"gold": {// gold coins details}
"neelam": // details
...etc
```

Or will it be different?
```

2021-03-15 05:29 UTC, correaswebert commented on models/wallets.js
> +    const { id } = await walletModel.add(walletData)
user-wallet is a one-one relation
so keeping the userId == walletId would be easier right?

2021-03-15 05:29 UTC, correaswebert commented on models/wallets.js
> +    if (res) {
return Boolean(res);