[WIPAdd authorization middleware based on roles
Real-Dev-Squad/website-backend pull request #339
Opened 2021-04-24 16:15 UTC by Cartmanishere

On backend, some of the routes are only allowed to be called for certain sets of users.
For e.g
- Super user (a.k.a @ankushdharkar )
- App owners (as defined by the list of mockdata in the repo)

Instead of writing different middleware for authorization of each particular type of user, 
this PR aims to provide a unified way of setting authorization for any route.

This is based on the user object having `roles` information.

A user object will contain the roles information as follows:
```json
{
    roles: {
        super_user: true,
                OR
        app_owner: true
    }
}
```

There is hierarchy of required roles. For e.g `superUser` has higher authority than `appOwner`. 
So any route which requires `appOwner`

2021-04-24 17:33 UTC, ankurnarkhede requested changes

2021-04-24 17:33 UTC, ankurnarkhede commented on middlewares/authorization.js
> +    let { roles } = req.userData
Add default as `{}` if roles is `undefined`.

2021-04-24 17:53 UTC, Cartmanishere commented on middlewares/authorization.js
> + * userRoles = {member: true, app_owner: true, super_user: true}
`member` is not used. update comment.

2021-04-30 15:57 UTC, ankurnarkhede requested changes
@Cartmanishere , added few comments.
Let me know if you can complete the roles strings to be defined as a constant by 1st May. Else, we can merge this PR and track it for later in an another issue.

2021-04-30 15:57 UTC, ankurnarkhede commented on firebase.json
> +      "port": 8081
This change can be reverted, @Cartmanishere!

2021-04-30 15:57 UTC, ankurnarkhede commented on routes/stocks.js
> +router.post('/', authenticate, authorizeUser('superUser'), createStock, addNewStock)
Can we have the strings `'superUser', 'appOwner', etc` defined as a constant and then use it here. We might mess up with the strings sometimes leading to an issue!

2021-05-13 16:30 UTC, ankurnarkhede approved these changes
LGTM ✅ 
To be merged after constants for roles are added or the corresponding issue is created.

2021-05-13 16:54 UTC, Cartmanishere commented
@ankurnarkhede Created an issue for the changes you have requested.

I will pick this up in sometime or if someone wants, they can work on it too.

https://github.com/Real-Dev-Squad/website-backend/issues/353

2021-05-13 16:56 UTC, merged