Unit tests for fetchUserTasks model function
Real-Dev-Squad/website-backend pull request #364
Opened 2021-05-29 21:21 UTC by bhk31

**Added unit test for these test cases**

![fetchUserTasks](https://user-images.githubusercontent.com/17399473/120084916-dd74c200-c0f1-11eb-93e6-992e33d3f585.PNG)

2021-05-30 18:00 UTC, swarajpure requested changes
This PR seems to be having refactoring along with tets
Can we have seperate PRs for both?
It becomes difficult to review multiple things happening

You can keep ONLY the refactoring part in this PR. 

For tests, you can create a new branch from this branch, keep all the tests in that branch and then commit from there, make a PR for the same. 
Make sure that the target branch for that PR is THIS branch (can be changed anytime from GitHub UI, not a big deal)

Please do the needful 🙂

2021-05-31 12:56 UTC, ankurnarkhede requested changes

2021-05-31 12:56 UTC, ankurnarkhede commented on utils/tasks.js
> +  if (type === 'group') {
Can we have this as a constant to be used elsewhere in the app?

2021-06-03 18:39 UTC, bhk31 commented
The test which is failed is fixed under this PR https://github.com/Real-Dev-Squad/website-backend/pull/369/files

2021-06-16 12:29 UTC, swarajpure requested changes
Some suggestions and some doubts, please check!

2021-06-16 12:29 UTC, swarajpure commented on test/unit/models/task.test.js
> +            startedOn: '1621728000',
Shouldn't these be numbers instead of string? 🤔

2021-06-16 12:29 UTC, swarajpure commented on test/unit/models/task.test.js
> +          startedOn: '1621728000',
re: number

2021-06-16 12:29 UTC, swarajpure commented on test/unit/models/task.test.js
> +        const allTasks = await tasks.fetchUserTasks(appOwner.username, ['active', 'pending', 'blocked'])
Since we're using this particular array again and again, better to have it coming from a variable?

2021-06-16 12:29 UTC, swarajpure commented on test/unit/models/task.test.js
> +  })
We aren't using sinon anywhere, why do we need this then?
We should be using `cleanDb` instead, in afterEach 🤔 

Can you please explain what's going on here? I'm a bit confused

2021-06-16 12:29 UTC, swarajpure commented on test/unit/models/task.test.js
> +          return task.status === 'completed'
better make of existing constants than using strings for task status

2021-06-24 10:43 UTC, sebuelias commented on test/unit/models/task.test.js
> +        if (task1.type === 'group') {
we have constants for tasks in constants/task.js -> TASK_STATUS and TASK_TYPE
Better we use them for the task type checks and task status checks

2023-11-06 20:10 UTC, closed without merging