Define CRUD operation for feature flag
Real-Dev-Squad/website-backend pull request #377
Opened 2021-06-07 16:29 UTC by Ankita2002-Fr

@Cartmanishere  @ankushdharkar @ASHWINIAJIT

I have worked on the CRUD operations for the feature flag and also added authentication and validation for the same.

Please review the PR!

2021-06-07 17:24 UTC, Cartmanishere requested changes
Add tests for these as well.

2021-06-07 17:24 UTC, Cartmanishere commented on controllers/featureFlags.js
> +      featureFlag
This should be passed under `data`.

```
{
  message: "..."
  data: <featureFlag>
}
```

2021-06-07 17:24 UTC, Cartmanishere commented on middlewares/validators/featureFlags.js
> +    config: joi.object().required()
Add validation for `enabled` field inside `config` object.

You can search for how to validate nested keys in joi.

2021-06-07 17:24 UTC, Cartmanishere commented on models/featureFlags.js
> +    const getImage = async (usersData) => {
this function is not needed. You can directly call `fetchUserImage` in the loop below.

2021-06-07 17:24 UTC, Cartmanishere commented on models/users.js
> +  // console.log(hash)
Remove the console.

2021-06-07 17:24 UTC, Cartmanishere commented on models/featureFlags.js
> +      const usersData = users.slice(start, end)
You can also do the logic in loop using just `i`.

Don't need `start` and `end` vars.

2021-06-17 17:45 UTC, swarajpure commented on controllers/featureFlags.js
> +    // console.log(res.status);
Commented code...?

2021-06-21 18:20 UTC, Ankita2002-Fr commented on controllers/featureFlags.js
> +    // console.log(res.status);
Removed!

2021-06-27 14:52 UTC, Cartmanishere submitted a review, later dismissed

2021-06-27 14:55 UTC, Cartmanishere commented
@Ankita2002-Fr Looks like your tests are failing due to unrelated change. See if you fix the test as well.

Also please, resolve the conflict merge conflict and update the PR.

Rest lgtm. We can merge it.

2021-06-28 14:36 UTC, Cartmanishere approved these changes

2021-06-30 03:56 UTC, merged