URL Shortner feature initial version
Real-Dev-Squad/website-backend pull request #390
Opened 2021-06-17 17:41 UTC by harshith-venkatesh

I am currently confused with using Regex or using valid-url package
https://www.npmjs.com/package/valid-url
Open To Suggestion
[ ] Tests to be added

2021-06-17 18:19 UTC, swarajpure requested changes
Some destructuring can be done
Please check 🙂

2021-06-17 18:19 UTC, swarajpure commented on models/urls.js
> +    return { id, longUrl: urlData.longUrl, shortUrl: urlData.shortUrl }
we can destructure `urlData` already

2021-06-17 18:19 UTC, swarajpure commented on models/urls.js
> +      return { id: urlData.id, longUrl: urlData.longUrl, shortUrl: urlData.shortUrl }
re: destructure

2021-06-19 00:42 UTC, harshith-venkatesh reviewed
@ankurnarkhede @sumitd94 @swarajpure

2021-06-19 00:42 UTC, harshith-venkatesh commented on controllers/urlShortner.js
> +const validUrlRegex = /^(?:(?:(?:https?|ftp):)?\/\/)(?:\S+(?::\S*)?@)?(?:(?!(?:10|127)(?:\.\d{1,3}){3})(?!(?:169\.254|192\.168)(?:\.\d{1,3}){2})(?!172\.(?:1[6-9]|2\d|3[0-1])(?:\.\d{1,3}){2})(?:[1-9]\
7:23  warning  Unsafe Regular Expression  security/detect-unsafe-regex
Currently receiving this warning 
I tried to resolve this issue but have not found the one which is resolving this warning
An alternative would be to install valid-url package which I did found would be overload which could be resolved with above statement

Open to suggestions :)

2022-08-03 15:17 UTC, Neha commented on controllers/urlShortner.js
> +const NOTVALIDURL = 'Please attach valid URL'
The words should be separated by the `underscore`

2022-08-03 15:17 UTC, Neha commented on controllers/urlShortner.js
> +const NOTVALIDURL = 'Please attach valid URL'
The words should be separated by the `underscore`

2022-08-03 15:17 UTC, Neha commented on controllers/urlShortner.js
> +      const shortUrl = 'RDS' + nanoid(6)
`RDS` should be moved to constant.

2022-08-03 15:17 UTC, Neha commented on controllers/urlShortner.js
> +        message: 'Url created successfully',
URL created...should be moved to Constant

2022-08-03 15:17 UTC, Neha commented on models/urls.js
> +    const snapshot = await urlsModel.where('longUrl', '==', longUrl).get()
`snapshot` of what? the variable name should be descriptive.

2022-08-03 15:17 UTC, Neha commented on controllers/urlShortner.js
> +    const fetchUrlData = await urlQuery.fetchUrl(shortUrl)
Question: What is the significance of the `data` in `fetchUrlData` here?

2022-08-03 15:20 UTC, Neha commented on controllers/urlShortner.js
> +        shortUrl: shortUrl,
As the key and value are the same we can remove the value and keep it  (https://javascript.info/object#property-value-shorthand)

{ 
    shortUrl,
  longUrl
}

2023-11-06 20:11 UTC, closed without merging

2023-11-06 20:12 UTC, prakashchoudhary07 commented
Closing this as we are having a separate backend for url-shortener in go #tiny-site-backend