dev -> main
Real-Dev-Squad/website-backend pull request #451
Opened 2021-11-30 19:12 UTC by swarajpure

2021-12-29 20:31 UTC, whyDontI requested changes
Needs changes
Refer - 
https://discord.com/channels/673083527624916993/735598747949465640/925833881846964325

2021-12-31 05:03 UTC, ankur-lt approved these changes

2021-12-31 05:03 UTC, ankur-lt commented
The 500 error on staging API is resolved. The issue was occurring due to read limits reached.

2021-12-31 05:04 UTC, ankurnarkhede approved these changes

2021-12-31 05:04 UTC, ankurnarkhede commented
The 500 error on staging API is resolved. The issue was occurring due to read limits reached.

2021-12-31 05:05 UTC, merged