new task status will be returned
Real-Dev-Squad/website-backend pull request #488
Opened 2022-01-11 11:10 UTC by akshay1502

Updating task status to the new task workflow while returning.

2022-01-11 15:08 UTC, Pavangbhat requested changes
Are we updating tasks with new task workflow status ? i.e
**active** → **IN_PROGRESS**, **unAssigned** → **AVAILABLE**

And also please note that the task is considered as active if it's in **BLOCKED**, **IN_PROGRESS**, **SMOKE_TESTING**

for reference ⬇️ 
![image](https://user-images.githubusercontent.com/45538392/148968001-cffc73c7-b245-4821-91cb-5b3e3a0838ae.png)

2022-01-15 12:09 UTC, prakashchoudhary07 approved these changes
looks good to me :+1:

2022-01-24 07:30 UTC, Pavangbhat requested changes
Hi, Akshay great work  🎉 
There are a few changes needed please work on it.

Also, make sure the following scenarios are handled 

- [ ] we can hit **/tasks/username?status=active** where we need to return tasks that are in either of the status **[active, blocked, completed, pending, IN_PROGRESS, BLOCKED,  SMOKE_TESTING, COMPLETED]**

- [ ] idle members are those who don't have a task which is either in [active, blocked, pending, IN_PROGRESS, BLOCKED,  SMOKE_TESTING]

2022-01-24 07:30 UTC, Pavangbhat commented on models/tasks.js
> +      taskData.status = TASK_STATUS[taskData.status]
Currently, we have task status as **pending** and **High Priority** please those cases as well

2022-01-28 06:52 UTC, Pavangbhat commented
This PR is continued with #514

2022-04-13 15:28 UTC, merged