fixed localhost response
Real-Dev-Squad/website-backend pull request #61
Opened 2020-10-13 10:58 UTC by sujitmohanty

1. Composed & defined a variable named `baseUrl` inside `config > development.js`
2. Assigned it to the concerned keys inside of rdsApi & rdsUi object literals.
3. Updated README.md
4. Immaculated code wherever necessary by removing all the console logs statements.

2020-10-14 02:00 UTC, ankurnarkhede requested changes
@sujitmohanty , seems like there are too many changes in this PR, most of which are around indentation. Can you remove them?
Also, seems like you are trying to redirect the login to localhost. This should not be environment specific.
Related issue: https://github.com/Real-Dev-Squad/website-backend/issues/62

2020-10-14 02:05 UTC, sujitmohanty commented
Ok Ankur.

On Wed, Oct 14, 2020, 07:31 Ankur Narkhede <notifications@github.com> wrote:

> *@ankurnarkhede* requested changes on this pull request.
>
> @sujitmohanty <https://github.com/sujitmohanty> , seems like there are
> too many changes in this PR, most of which are around indentation. Can you
> remove them?
> Also, seems like you are trying to redirect the login to localhost. This
> should not be environment specific.
> Related issue: #62
> <https://github.com/Real-Dev-Squad/website-backend/issues/62>
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/Real-Dev-Squad/website-backend/pull/61#pullrequestreview-507942687>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ALHA75LN6F257YKCGRMCNNDSKUA6JANCNFSM4SOTURVQ>
> .
>

2020-10-14 23:29 UTC, ankurnarkhede requested changes

2020-10-14 23:29 UTC, ankurnarkhede commented on controllers/authController.js
> +  const authRedirectionUrl = `${config.get(
Can you remove all the unwanted code formatting from the PR?
Please submit PR with changes only in the code ehich id to be modified.
Seems your local code formatter is messing the code!

2020-10-15 19:01 UTC, sujitmohanty commented
I had removed all the "unwanted" code formatting on Oct 14 itself, after I
was intimated about them. If they still persist in a specific file/files,
please let me know. I have had removed them meticulously and am unable to
discover anything in usersController.js

On Thu, Oct 15, 2020 at 5:00 AM Ankur Narkhede <notifications@github.com>
wrote:

> *@ankurnarkhede* requested changes on this pull request.
> ------------------------------
>
> In controllers/authController.js
> <https://github.com/Real-Dev-Squad/website-backend/pull/61#discussion_r505065984>
> :
>
> > @@ -13,38 +13,44 @@ const authService = require('../services/authService')
>   */
>  const githubAuth = (req, res, next) => {
>    let userData
> -  const authRedirectionUrl = `${config.get('services.rdsUi.baseUrl')}${config.get('services.rdsUi.routes.authRedirection')}`
> +  const authRedirectionUrl = `${config.get(
>
> Can you remove all the unwanted code formatting from the PR?
> Please submit PR with changes only in the code ehich id to be modified.
> Seems your local code formatter is messing the code!
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/Real-Dev-Squad/website-backend/pull/61#pullrequestreview-508839685>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ALHA75OHZT54NUEND2R4PE3SKYX7XANCNFSM4SOTURVQ>
> .
>

2021-01-09 17:25 UTC, Rucha1499 commented
Fixed this issue in #127 . 
Therefore, closing this one.

2021-01-09 17:25 UTC, closed without merging