Enhance idle member API
Real-Dev-Squad/website-backend pull request #643
Opened 2022-07-30 16:43 UTC by SanthoshBalagur

Closes #619

2022-08-05 15:38 UTC, alishvagadiya commented on models/users.js
> +      call = call.where(key, "==", query[key]);
It's not good practice to use dynamic column name selection. checkout and read xss injection

2022-08-11 14:11 UTC, alishvagadiya commented on controllers/members.js
> +const users = require("../models/users");
Taking a complete model into one object, it's better to use the import required particular function, using destructing.

2022-08-11 14:14 UTC, alishvagadiya commented on controllers/members.js
> +    const allusers = await users.queryUser({ status: "idle" });
Variable name should be `idleUsers` instead of `allusers`

2022-08-11 14:21 UTC, alishvagadiya requested changes
Look into the requested changes and comment in this pull request.

2022-09-15 06:19 UTC, closed without merging

2022-09-15 06:19 UTC, ankushdharkar commented
Will be taken care of in another PR. The initial author has been MIA.