Automation for checking local development environment is properly setup or not.
Real-Dev-Squad/website-backend pull request #81
Opened 2020-11-10 15:10 UTC by takshch

#51

2020-11-14 01:34 UTC, ankurnarkhede requested changes

2020-11-17 14:10 UTC, takshch commented on local-test.js
> +if (firestoreData === '' || firestoreData === null || firestoreData === undefined) {
Changed to if (!firestoreData)

2020-11-17 14:19 UTC, takshch commented on package.json
> +    "dev": "node local-test.js && cross-env NODE_ENV=development nodemon server.js",
Done

2020-11-17 14:21 UTC, takshch commented on local-test.js
> +  !config.githubOauth ||
No. Only oauth authentication.

2020-11-17 15:13 UTC, closed without merging