Add user profile w.r.t the userID
Real-Dev-Squad/website-backend pull request #877
Opened 2022-12-16 10:39 UTC by Maheima

2022-12-16 11:05 UTC, RitikJaiswal75 requested changes
Mahima please write tests supporting this.

2022-12-16 15:18 UTC, Maheima commented on test/fixtures/user/user.js
> +        url: "https://res.cloudinary.com/realdevsquad/image/upload/v1667685133/profile/mtS4DhUvNYsKqI7oCWVB/aenklfhtjldc5ytei3ar.jpg",
Added picture field in users fixture because we were getting it in the Prod but there was no test for it.

2022-12-17 00:47 UTC, heyrandhir submitted a review, later dismissed
LGTM

2022-12-17 07:06 UTC, rohan09-raj commented on controllers/userStatus.js
> +    for (const doc of allUserStatus) {
Can we name each doc as `user`?

2022-12-17 07:14 UTC, RitikJaiswal75 commented on test/integration/userStatus.test.js
> +          res.body.allUserStatus.forEach((doc) => {
let's use status instead of `doc`

2022-12-18 23:51 UTC, RitikJaiswal75 approved these changes
LGTM

2022-12-19 00:03 UTC, merged