Fixing api route users/userId/{userId} #966
Real-Dev-Squad/website-backend pull request #967
Opened 2023-03-25 05:26 UTC by endeavourmonk

The api route users/userId/{userId} changed to users/{userId}, along with this all the places where this api is used.

2023-03-26 17:15 UTC, vikhyat187 commented on routes/users.js
> +router.get("/users/:userId", users.getUserById);
why did we add `/users` this is already present in the `index.js ` file as /users is the base url. @endeavourmonk

2023-03-26 17:22 UTC, vikhyat187 requested changes

2023-03-26 17:22 UTC, vikhyat187 commented on routes/users.js
> +router.get("/users/:id/skills", users.getUserSkills);
this need not be changed

2023-03-26 17:22 UTC, vikhyat187 commented on routes/users.js
> +router.get("/users/suggestedUsers/:skillId", authenticate, authorizeRoles([SUPERUSER]), users.getSuggestedUsers);
need not change this

2023-03-30 05:20 UTC, endeavourmonk reviewed
users/userId/{userId} to users/?id=abc

2023-04-04 16:10 UTC, vikhyat187 commented
LGTM!

2023-04-04 16:33 UTC, vikhyat187 submitted a review, later dismissed

2023-04-05 11:48 UTC, heyrandhir commented
> The api route users/userId/{userId} changed to users/{userId}, along with this all the places where this api is used.

Is the description correct ? I think its query params not path params.

2023-04-05 11:49 UTC, heyrandhir commented
tests are failing. can you please check @endeavourmonk

2023-04-05 11:51 UTC, heyrandhir requested changes

2023-04-05 11:51 UTC, heyrandhir commented on controllers/users.js
why have you removed constants everywhere and hardcoding the messages ?

2023-04-05 12:28 UTC, endeavourmonk commented on controllers/users.js
Updated to hardcoded to the constants

2023-04-05 16:49 UTC, prakashchoudhary07 requested changes

2023-04-05 16:49 UTC, prakashchoudhary07 commented on routes/users.js
>  router.get("/", authenticate, userValidator.getUsers, users.getUsers);
Will `/users` API work as expected after this change?

2023-04-06 00:41 UTC, vikhyat187 commented
> tests are failing. can you please check @endeavourmonk

I think @endeavourmonk has updated wrong test, he has changed https://github.com/Real-Dev-Squad/website-backend/pull/991
The test for `/users/id` this API, but this doesn't exist right? correct me if I'm wrong.

Ideally he should make change in this https://github.com/Real-Dev-Squad/website-backend/blame/6919649f1761009a06a72254e0d2734e57b94d07/test/integration/users.test.js#LL465

cc : @endeavourmonk @prakashchoudhary07

2023-04-25 01:01 UTC, closed without merging